version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{s3_bucket_url}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
       nodejs: 22
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - npm run build
        - aws s3 rm s3://everything.education.web.dev --recursive
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/everything.education.web'
    discard-paths: no
